## 1. Numpy快速入门

## 2. Numpy基础

### 2.1 Numpy数组对象

In [ ]:
import numpy as np

In [ ]:
a = np.arange(5)

In [ ]:
a

In [5]:
a.dtype #用的是32位python

dtype('int32')

In [6]:
a.shape  #数组 的 shape 属性返回 一个元 组（ tuple）， 元 组 中的 元素 即为 NumPy 数组 
#每一个 维 度 上 的 大小。 上面 例子 中的 数组 是一 维 的， 因此 元 组 中 只有 一个 元素。


(5,)

### 2.2 创建多维数组

In [7]:
m = np.array([np.arange(2), np.arange(2)])

In [8]:
m

array([[0, 1],
       [0, 1]])

In [9]:
m.shape

(2, 2)

In [10]:
#Create  a 3-dimension array
m3 = np.array([np.arange(2),np.arange(2),np.arange(2)])

In [11]:
m3

array([[0, 1],
       [0, 1],
       [0, 1]])

#### 2.2.1 选取数组元素

In [12]:
#首先来创建一个多维数组
a = np.array([[1,2],[3,4]])

In [13]:
a

array([[1, 2],
       [3, 4]])

In [14]:
#选取数组中的元素
a[0,0]

1

In [15]:
a[0,1]

2

In [16]:
a[1,0]

3

In [17]:
a[1,1]

4

总结：选取数组元素的办法是利用索引来逐步指定到相应的元素。索引从0开始。

#### 2.2.2 Numpy数据类型

<img src="数据类型.png">

In [18]:
#每一种数据类型都有相应的类型转换函数
np.float(30)

30.0

In [19]:
np.bool(25)

True

In [20]:
np.int32(2.4)

2

In [21]:
# numpy中很多函数的参数可以指定数据类型
a = np.arange(7, dtype="uint16") #注意书上此处参数uint16不带引号（出错）

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [23]:
a.dtype

dtype('uint16')

#### 2.2.3数据类型对象

* 数据类型对 是numpy.dtype类的实例。
* 如前所述，NumPy数组是有数据类型的，更确切地说，NumPy 数组中的每一个元素均为相同的数据类型。
* 数据类型对象可以给出单个数组元素在内存中占用的字节数，即dtype类的itemsize属性：

In [24]:
a.dtype.itemsize

2

#### 2.2.4 字符编码

* 字符编码用来表示数据类型，是为了兼容numpy前身Numeric
* 我不 推荐 使用 字符 编码， 但 有时 会用 到， 因此 下面 还是 列出 了 字符 编码 的 对应 表。
* 读者 应该 优先 使用 dtype 对象 来表示 数据 类型， 而 不是 这些 字符 编码。


<img src="字符编码.png" />

In [25]:
#创建一个单精度浮点数组
a = np.arange(7, dtype="f")

In [26]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.], dtype=float32)

In [27]:
##创建一个复数数组
b = np.arange( 7, dtype='D')

In [28]:
b

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j])

#### 2.2.5 自定义数据类型

In [30]:
# 完整的Numpy数据类型列表
np.sctypeDict.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 'bool', 22, 23, 'float32', 'short', 'UInt16', 'Str0', 'int32', 'float_', 'M', 'U', 'F', 'object0', 'h', 'Q', 'b1', 'Float64', 'm', 'd', 'i8', 'Timedelta64', 'uintc', 'b', 'str_', 'M8', 'int8', 'csingle', 'str', 'f2', 'int16', 'complex64', 'int64', 'L', 'long', 'uintp', 'S', 'Float32', 'g', 'i4', 'void0', 'bool8', 'uint0', 'UInt64', 'intc', 'clongfloat', 'u1', 'e', 'I', 'i', 'V', 'int_', 'q', 'Int16', 'longdouble', 'c8', 'intp', 'single', 'unicode', 'c16', 'half', 'unicode_', 'float16', 21, 'i1', 16, 'complex_', 'ubyte', 'Void0', 'f4', 'longcomplex', 'G', 'm8', 'cfloat', 'float', 'Int64', 'double', 'O', 'longfloat', 'object', '?', 'p', 'ulonglong', 'Complex32', 'l', 'float64', 'singlecomplex', 'complex', 'D', 'f', 'datetime64', 'Bool', 'bytes', 'Int8', 'uint64', 'Float16', 'f8', 'int0', 'longlong', 'u2', 'Int32', 'Datetime64', 'cdouble', 'u8', 'a', 'uint8', 'timedelta64', 'string_', 'int', 'Complex64', 'str

#### 2.2.6 dtype类的属性

In [33]:
#dtype类有很多的属性，例如，我们可以获取数据类型的字符编码
t = np.dtype("Float64")

In [35]:
t.char

'd'

In [38]:
t.type

numpy.float64

In [40]:
#str属性给出数据类型的字符串表示，暂时看不懂
t.str

'<f8'

### 2.3 创建自定义数据类型

In [58]:
#作为 示例， 我们将 创建 一个 存储 商店 库存 信息 的 数据 类型。
#其中， 我们 用 一个 长度 为 40 个 字符 的 字符串 来 记录 商品 名称， 用 一个 32 位 的 
#整数 来 记录 商品 的 库存 数量， 最后 用 一个 32 位 的 单 精度 浮 点数 来 记录 商品 价格。

t= np.dtype([('name',str,40), ('numitems', 'int32'),('price', 'float32')])

In [53]:
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [60]:
t['name']

dtype('<U40')

In [63]:
itemz = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)], dtype=t)

In [65]:
itemz[1]

('Butter', 13, 2.7200000286102295)

In [1]:
print('hello')

hello
